### ISSUE TITLE
Dockerize webapp

### ISSUE THREAD

**Issue by franciscohanna92** [FightCOVID19/webapp#3]

**Comment by elcronos** [comment]
I can take care of this one

**Comment by paladium** [comment]
We have already merged the commit that fixes this issue :)

**Comment by JuanSeBestia** [comment]
I think it Is not necessary, not is better upload in bucket like static files and use S3 and edge system

See https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
